# Generated by Django 3.1.7 on 2021-03-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('subtype', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('d_next', models.DateTimeField(auto_now_add=True)),
                ('d_done', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('system', models.CharField(max_length=100)),
            ],
        ),
    ]
