# Generated by Django 3.1.7 on 2021-10-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='capacitor',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='valvula',
            name='item_ptr',
        ),
        migrations.DeleteModel(
            name='Atornillador',
        ),
        migrations.DeleteModel(
            name='Capacitor',
        ),
        migrations.DeleteModel(
            name='Valvula',
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.itemtype'),
        ),
    ]
