# Generated by Django 3.1.7 on 2021-03-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='action_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='d_done',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='d_next',
            field=models.DateTimeField(),
        ),
    ]
