# Generated by Django 3.1.7 on 2021-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0002_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiro',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
