# Generated by Django 3.1.7 on 2021-10-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0002_auto_20211001_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='RPM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='capacitancia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pulgadas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='voltaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
