# Generated by Django 3.1.7 on 2021-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('data_loader', '0002_auto_20210311_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='system',
        ),
        migrations.AddField(
            model_name='component',
            name='assigned_to',
            field=models.ManyToManyField(to='people.Profile'),
        ),
    ]
