# Generated by Django 3.1.7 on 2021-10-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0003_retiro_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='taken',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_units',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
