# Generated by Django 3.1.7 on 2021-03-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('data_loader', '0003_auto_20210312_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='component',
            name='assigned_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.profile'),
        ),
    ]
