# Generated by Django 3.1.7 on 2021-03-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0004_auto_20210312_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='component',
            name='assigned_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_loader.person'),
        ),
    ]
