# Generated by Django 3.1.7 on 2021-03-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0005_auto_20210312_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='component',
            name='assigned_to',
            field=models.ManyToManyField(to='data_loader.Person'),
        ),
    ]
