# Generated by Django 3.1.7 on 2021-10-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0006_auto_20211019_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier_pn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
