# Generated by Django 3.1.7 on 2021-03-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0001_initial'),
        ('data_loader', '0006_auto_20210312_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.stage'),
        ),
        migrations.AlterField(
            model_name='component',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.track'),
        ),
    ]
