# Generated by Django 3.1.7 on 2021-03-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0001_initial'),
        ('data_loader', '0008_component_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('d_next', models.DateTimeField()),
                ('d_done', models.DateTimeField()),
                ('action', models.CharField(max_length=100)),
                ('action_date', models.DateTimeField()),
                ('assigned_to', models.ManyToManyField(to='data_loader.Person')),
                ('depends_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.system')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.stage')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.track')),
            ],
        ),
    ]
