# Generated by Django 3.1.7 on 2021-03-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0009_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.system'),
        ),
    ]
