# Generated by Django 3.1.7 on 2021-03-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0010_auto_20210315_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='assigned_to_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.system'),
        ),
    ]
