# Generated by Django 3.1.7 on 2021-03-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0001_initial'),
        ('data_loader', '0011_component_assigned_to_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='action_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='system',
            name='action_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('d_next', models.DateTimeField()),
                ('d_done', models.DateTimeField()),
                ('action', models.CharField(blank=True, max_length=100)),
                ('action_date', models.DateTimeField(blank=True)),
                ('assigned_to', models.ManyToManyField(to='data_loader.Person')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.stage')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.track')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='assigned_to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.project'),
        ),
    ]
