# Generated by Django 3.1.7 on 2021-03-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0013_auto_20210315_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='assigned_to',
            new_name='assigned_to_person',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='assigned_to',
            new_name='assigned_to_person',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='assigned_to',
            new_name='assigned_to_person',
        ),
    ]
