# Generated by Django 3.1.7 on 2021-03-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0015_auto_20210318_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='action_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='d_done',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='d_next',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='system',
            name='action_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='d_done',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='system',
            name='d_next',
            field=models.DateField(),
        ),
    ]
