# Generated by Django 3.1.7 on 2021-09-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0017_auto_20210917_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='assigned_to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.project'),
        ),
    ]
