# Generated by Django 3.1.7 on 2021-09-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0002_stage_tag'),
        ('data_loader', '0018_item_assigned_to_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('subtype', models.CharField(max_length=100)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('d_next', models.DateField(null=True)),
                ('d_done', models.DateField(null=True)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('action_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='depends_on',
        ),
        migrations.AddField(
            model_name='project',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='d_done',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='d_next',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.stage'),
        ),
        migrations.AddField(
            model_name='project',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.track'),
        ),
        migrations.AddField(
            model_name='system',
            name='action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='system',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='d_done',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='d_next',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.stage'),
        ),
        migrations.AddField(
            model_name='system',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.track'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
        migrations.AddField(
            model_name='component',
            name='assigned_to_person',
            field=models.ManyToManyField(to='data_loader.Person'),
        ),
        migrations.AddField(
            model_name='component',
            name='assigned_to_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.system'),
        ),
        migrations.AddField(
            model_name='component',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.stage'),
        ),
        migrations.AddField(
            model_name='component',
            name='supplied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.supplier'),
        ),
        migrations.AddField(
            model_name='component',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.track'),
        ),
    ]
