# Generated by Django 3.1.7 on 2021-09-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0019_auto_20210917_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
