# Generated by Django 3.1.7 on 2021-09-17 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0020_auto_20210917_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='action',
        ),
        migrations.RemoveField(
            model_name='project',
            name='action_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='d_done',
        ),
        migrations.RemoveField(
            model_name='project',
            name='d_next',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='track',
        ),
        migrations.RemoveField(
            model_name='system',
            name='action',
        ),
        migrations.RemoveField(
            model_name='system',
            name='action_date',
        ),
        migrations.RemoveField(
            model_name='system',
            name='d_done',
        ),
        migrations.RemoveField(
            model_name='system',
            name='d_next',
        ),
        migrations.RemoveField(
            model_name='system',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='system',
            name='track',
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.project'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.AddField(
            model_name='item',
            name='assigned_to_person',
            field=models.ManyToManyField(to='data_loader.Person'),
        ),
        migrations.AddField(
            model_name='item',
            name='assigned_to_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.system'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.supplier'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.itemtype'),
        ),
    ]
