# Generated by Django 3.1.7 on 2021-09-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0022_item_assigned_to_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='assigned_to_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='assigned_to_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='assigned_to_system',
            new_name='system',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='assigned_to_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='assigned_to_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='assigned_to_project',
            new_name='project',
        ),
    ]
