# Generated by Django 3.1.7 on 2021-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0025_auto_20210917_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='load_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
