# Generated by Django 3.1.7 on 2021-09-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0026_item_load_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='load_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
