# Generated by Django 3.1.7 on 2021-09-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0029_auto_20210923_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Something',
        ),
    ]
