# Generated by Django 3.1.7 on 2021-09-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0030_delete_something'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atornillador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RPM', models.IntegerField(blank=True, null=True)),
                ('torque', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.atornillador'),
        ),
    ]
