# Generated by Django 3.1.7 on 2021-09-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0032_auto_20210923_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atornillador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='atornillador',
            name='torque',
        ),
        migrations.AddField(
            model_name='atornillador',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_loader.item'),
            preserve_default=False,
        ),
    ]
