# Generated by Django 3.1.7 on 2021-09-23 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0033_auto_20210923_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_loader.item')),
                ('capacitancia', models.IntegerField(blank=True, null=True)),
                ('voltaje', models.IntegerField(blank=True, null=True)),
            ],
            bases=('data_loader.item',),
        ),
    ]
