# Generated by Django 3.1.7 on 2021-09-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0034_capacitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atornillador',
            options={'verbose_name_plural': 'atornilladores'},
        ),
        migrations.AlterModelOptions(
            name='capacitor',
            options={'verbose_name_plural': 'capacitores'},
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
