# Generated by Django 3.1.7 on 2021-09-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0035_auto_20210924_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('Atornillador', 'Atornillador'), ('Capacitor', 'Capacitor')], max_length=100, null=True),
        ),
    ]
