# Generated by Django 3.1.7 on 2021-09-24 18:23

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0037_auto_20210924_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='depends_on',
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data_loader.project'),
        ),
    ]
