# Generated by Django 3.1.7 on 2021-09-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0040_delete_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manufacturer_pn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
