# Generated by Django 3.1.7 on 2021-09-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0042_valvula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valvula',
            name='pugladas',
        ),
        migrations.AddField(
            model_name='valvula',
            name='pulgadas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('Atornillador', 'Atornillador'), ('Capacitor', 'Capacitor'), ('Valvula', 'Valvula')], max_length=100, null=True),
        ),
    ]
