# Generated by Django 3.1.7 on 2021-11-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsubtype',
            name='prefix',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
