# Generated by Django 3.1.7 on 2021-03-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
