# Generated by Django 3.1.7 on 2021-03-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0005_auto_20210312_1641'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
